server:
    port: 9000
    ssl:
        key-store: classpath:www.upcl.ltd.pfx     #证书的路径
        key-store-password: q9iW0iI0        #证书密码
        key-store-type: PKCS12              #秘钥库类型

pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: false


spring:
    datasource:
        url: jdbc:mysql://39.106.189.36:3306/grain_zxl?useSSL=false
        username: root
        password: Lhqs$1314
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        initial-size: 10
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 3000000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        filters: stat,wall



#mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
#    mapper-locations: classpath:mybatis/mapper/*.xml
